spring:
  datasource: 
    url: jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=${DB_NAME:sensitewords}
    username:  ${DB_USER:sa}
    password: ${DB_PASS:AV3ryStron9Pa55Word}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

server: 
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG